#!/bin/bash



read -p "Enter the file name: " file_name



touch $file_name



echo "#!/bin/bash" > $file_name



vi $file_name



chmod u+x $file_name



git add .



git commit -m '2-shell_redirections'



git push


